build:
  dir: .zip
  functions: functions
functions:
  send_confirmation_email:
    version: 0.1.0
    target_source_code_dir: send-confirmation-email
    zip_path: send-confirmation-email.zip
  test_ydb:
    version: 0.0.2
    target_source_code_dir: test-ydb
    zip_path: test-ydb.zip
